---
- hosts: monitoring
  gather_facts: yes
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=86400

  roles:
    - geerlingguy.apache
    - geerlingguy.munin
    - geerlingguy.munin-node

  tasks:
# Add ammended apache munin VHost configuration
    - name: Ammend apache.conf Munin VHost configuration for Apache 2.4
      copy:
        src: "files/munin-apache.conf"
        dest: "/etc/munin/apache.conf"
        owner: root
        group: root
        mode: 0644
