---
# ===============================================================================
# FOR FINE-TUNNING THESE DEFAULTS SHOULD BE OUT-COMMENTED, AND SUBSTITUTED 
# DEPENDING ON THE GROUP OR HOST,THROUGH group-vars OR hostvars DEFINED VARIABLES

# OVERWRITTEN THROUGH hostvars DEFINED VARIABLES
#  # Backup cron job options.
#  backup_cron_job_state: present             # default value
#  backup_hour: "*"
#  backup_minute: "10"

# User under which backup jobs will run.
backup_user: backup

# Path to where backups configuration will be stored.
backup_path: /home/{{ backup_user }}/backup_conf

# OVERWRITTEN THROUGH hostvars DEFINED VARIABLES
#  # Directories to back up. {{ backup_user }} must have read access to these dirs.
#  backup_directories:
#    - /home/{{ backup_user }}
#    - /opt/railsapp/log
#    - /etc/crontab
#  #  - /home/{{ backup_user }}/domains       # default value
#  #  - /home/{{ backup_user }}/repositories  # default value
#  
#  # Items to exclude from backups. (Use rsync 'excludes' file syntax.)
#  backup_exclude_items:
#    - .DS_Store
#  #  - cache
#  #  - tmp
# ===============================================================================
# Options to control where the backup is delivered.
backup_identifier: "{{ inventory_hostname }}"
backup_remote_connection: "{{ backup_user }}@192.168.1.10"
backup_remote_base_path: "/share/homes/backup/backups"
backup_remote_connection_ssh_options: '-o StrictHostKeyChecking=no'

# Add your server's host key to ensure seamless backup functionality.
#backup_remote_host_name: '192.168.1.10'
#backup_remote_host_key: "{{ lookup('file', '/Users/antonio/.ssh/id_rsa.pub') }}" #  Mac
# ================================================================================
# MySQL database backup options.

backup_mysql: ('db' in group_names)  # true ONLY IF MYSQL INSTALLED
# backup_mysql: false  # The role default value is now false, because I changed it; 
#   (see details in main Readme.txt and roles/geerlingguy.backup/defaults/main.yml)
backup_mysql_user: dbdump
backup_mysql_password: password
backup_mysql_credential_file: ''
# ================================================================================
