---
# ======================================================================
# Variables for filebeat configuration
filebeat_modules:
  - module: nginx
  - module: postgresql
  - module: mysql
  - module: system
  - module: elasticsearch
  - module: logstash
  - module: kibana

filebeat_inputs_paths_logs:
  - /var/log/syslog
  - /opt/railsapp/log/production.json
  - /opt/railsapp/log/puma.stdout.log
  - /opt/railsapp/log/puma.stderr.log

filebeat_inputs_paths_json:
  - /var/log/syslog
  - /opt/railsapp/log/production.json
  - /opt/railsapp/log/puma.stdout.log
  - /opt/railsapp/log/puma.stderr.log




# To be deleted when not using the geerlingguy role  
filebeat_create_config: false









