---
# MAIN
- src: geerlingguy.git
- src: geerlingguy.nodejs
- src: rvm.ruby

# COMMON SERVICES
- src: geerlingguy.firewall
- src: geerlingguy.ntp
- src: geerlingguy.security

# ELK
- src: geerlingguy.java
- src: geerlingguy.elasticsearch
- src: geerlingguy.kibana
#- src: geerlingguy.logstash
