---
# =============================================================================
# Services to be monitored by monit checks ( etc/monit/conf.d/)
# See playbook common/monit/vars.yml
monit_checked_services:
#  - apache
  - backup  
  - cron
#  - elasticsearch
#  - kibana
#  - logstash
#  - mysql
  - nginx
  - ntp
#  - postfix
  - postgresql
  - postgresql_replica # THIS CHECK MUST BE SET ON MASTER  
  - puma
  - rsyslog
  - ssh
  - system
# =============================================================================
# MySQL replication: master or slave role
# See playbook mysql/vars.yml and inventory(these variables lived there before)
mysql_replication_role: slave
mysql_server_id: 2
# =============================================================================
# Backups

# Scheduling of backup cron jobs.You should stagger backup times among servers,
# so your backup server doesn't get a huge influx of data at once.
# Backup cron job options.
backup_cron_job_state: present             # default value
backup_hour: "02"            # Stagger backup times among servers
backup_minute: "00"         # Stagger backup times among servers

# Directories and files to back up.
# The {{ backup_user }} must have read access to these dirs.
# See playbook common/backup/vars.yml
backup_directories:
  - /home/{{ backup_user }}/backup_conf
#  - /opt/railsapp/log
  - /etc/crontab
#  - /home/{{ backup_user }}/domains       # default value
#  - /home/{{ backup_user }}/repositories  # default value

# Items to exclude from backups. (Use rsync 'excludes' file syntax.)
backup_exclude_items:
  - .DS_Store
#  - cache
#  - tmp
# =============================================================================
