---
- hosts: db
  become: true  # you need sudo

  vars_files:
  - vars.yml

  pre_tasks:
  - name: package update (apt)
    apt: update_cache=yes cache_valid_time=3600

  roles:
  - role: geerlingguy.postgresql