---
- hosts: db
  become: true  # you need sudo

  handlers:
  - name: restart postgresql
    service:
      name: postgresql
      state: restarted

  tasks:
  - name: package update (apt)
    apt: update_cache=yes cache_valid_time=3600

  - name: Install app dependencies for postgresql 
    apt:
      name: ['postgresql','postgresql-client','libpq-dev','python-psycopg2']
      state: present
    
  - name: Set Postgresql config listening to all addresses 
    lineinfile:
      path: "/etc/postgresql/9.5/main/postgresql.conf"
      regexp: "^#?listen_addresses = 'localhost'"
      backrefs: yes
      line: "listen_addresses = '*'"
    notify: restart postgresql