---
#=================================================================================
# FOLLOWING VARIABLES ARE ONLY USED FOR DB DUMPS

# OJO CON LA ASIGNACION DE backup COMO dump_user
# ES EL MISMO USUARIO DEL backup PLAYBOOK (playbooks/common/backup/main.yml)
# PARA SEPARARLO HABRÍA QUE EJECUTAR CON EL NUEVO LOS PRIMEROS5 TASKS DEL backup PLAYBOOK
# (PARA QUE EXISTA, TENGA CARPETA, TENGA CONFIGURACION Y CLAVES DE SSH)
# User under which backup jobs will run.
dump_user: backup
# Path to where backups configuration will be stored.
dump_path: /home/{{ dump_user }}/dump_conf

# PROBABLY TO BE OVERWRITTEN THROUGH hostvars DEFINED VARIABLES
# Databases to be dumped
psql_dump_databases:
  - railsapp_production

# Options to control where the db_dump is delivered.
dump_identifier: "{{ inventory_hostname }}"
dump_remote_connection: "{{ dump_user }}@192.168.1.10"
dump_remote_base_path: /share/homes/{{ dump_user }}
dump_remote_connection_ssh_options: '-o StrictHostKeyChecking=no'
# Options to control when the db_dump is delivered
dump_cron_job_state: present             # default value
dump_hour: "03"            # Stagger backup times among servers
dump_minute: "00"

#=================================================================================
# FOLLOWING VARIABLES ARE ONLY USED FOR DB REPLICATION
# SEE. https://github.com/samdoran/ansible-role-pgsql-replication
pgsqlrep_group_name: replica
pgsqlrep_group_name_master: db
pgsqlrep_master_address: "{{ groups['db'][0] }}"       # IF YOU WANT REPLICATION
pgsqlrep_replica_address: "{{ groups['replica'][0] }}" # DON'T FORGET TO SET THIS
                                                       # DON'T FORGET TO SET THIS
# PROBABLY YOU WILL NEVER CHANGE ANY OF THE FOLLOWING 
pgsqlrep_config_path: /etc/postgresql/9.5/main
pgsqlrep_data_path: /var/lib/postgresql/9.5/main
pgsqlrep_user: replicator
pgsqlrep_password: replicator               # Store this in an Ansible vault
pgsqlrep_wal_level: hot_standby
pgsqlrep_max_wal_senders: "{{ groups[pgsqlrep_group_name] | length * 2 }}"
pgsqlrep_wal_keep_segments: 100
pgsqlrep_synchronous_commit: local
pgsqlrep_application_name: postgresql_replica

pgsqlrep_postgres_conf_lines:
  - regexp: '#?wal_level = \w+(\s+#.*)'
    line: 'wal_level = {{ pgsqlrep_wal_level }}\1'

  - regexp: '#?max_wal_senders = \d+(\s+#.*)'
    line: 'max_wal_senders = {{ pgsqlrep_max_wal_senders }}\1'

  - regexp: '#?wal_keep_segments = .*(\s+#.*)'
    line: 'wal_keep_segments = {{ pgsqlrep_wal_keep_segments }}\1'

  - regexp: '#?synchronous_standby_names = .*'
    line: "synchronous_standby_names = '{{ pgsqlrep_application_name }}'"

  - regexp: '#?synchronous_commit = \w+(\s+#.*)'
    line: 'synchronous_commit = {{ pgsqlrep_synchronous_commit }}\1'
#=================================================================================
