---
# THESE DEFAULTS SHOULD BE OVERWRITTEN, DEPENDING ON THE GROUP OR HOST,
# THROUGH group-vars OR hostvars DEFINED VARIABLES
# OVERWRITTEN THROUGH hostvars DEFINED VARIABLES
#logrotate_scripts:
#  - monit
#  - mysql-server
#  - nginx
#  - railsapp
#  - rsyslog
