---
- hosts: db
  become: true  # you need sudo

  vars_files:
    - vars.yml

  handlers:
  - name: restart postgresql
    service:
      name: postgresql
      state: restarted

  tasks:
  - name: Configure master server
    lineinfile:
      state: present
      backrefs: true
      dest: "{{ pgsqlrep_config_path }}/postgresql.conf"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items: "{{ pgsqlrep_postgres_conf_lines }}"
    notify: restart postgresql
  
  - name: Create replication user account
    postgresql_user:
      name: "{{ pgsqlrep_user }}"
      password: "{{ pgsqlrep_password }}"
      role_attr_flags: replication
    become: true
    become_user: postgres
    # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
    # Avoid problems becoming postgres user
    vars:
      ansible_ssh_pipelining: true
        
  - name: Add trust in pg_hba.conf
    lineinfile:
      state: present
      dest: "{{ pgsqlrep_config_path }}/pg_hba.conf"
      regexp: 'host.*replication.*{{ item }}/32.*trust'
      line: 'host    replication    {{ pgsqlrep_user }}  {{ item }}/32 trust'
    become: yes
    become_user: postgres
    # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
    # Avoid problems becoming postgres user
    vars:
        ansible_ssh_pipelining: true
    with_items: "{{ pgsqlrep_replica_address }}"
    notify: restart postgresql
