---
pgsqlrep_config_path: /etc/postgresql/9.5/main
pgsqlrep_data_path: /var/lib/postgresql/9.5/main
pgsqlrep_user: replicator
pgsqlrep_password: replicator # Store this in an Ansible vault
pgsqlrep_wal_level: hot_standby
pgsqlrep_max_wal_senders: "{{ groups[pgsqlrep_group_name] | length * 2 }}"
pgsqlrep_wal_keep_segments: 100
pgsqlrep_synchronous_commit: local
pgsqlrep_application_name: postgresql_replica

pgsqlrep_group_name: replica
pgsqlrep_group_name_master: db

pgsqlrep_master_address: "{{ groups['db'][0] }}"
pgsqlrep_replica_address: "{{ groups['replica'][0] }}"

pgsqlrep_postgres_conf_lines:
  - regexp: '#?wal_level = \w+(\s+#.*)'
    line: 'wal_level = {{ pgsqlrep_wal_level }}\1'

  - regexp: '#?max_wal_senders = \d+(\s+#.*)'
    line: 'max_wal_senders = {{ pgsqlrep_max_wal_senders }}\1'

  - regexp: '#?wal_keep_segments = .*(\s+#.*)'
    line: 'wal_keep_segments = {{ pgsqlrep_wal_keep_segments }}\1'

  - regexp: '#?synchronous_standby_names = .*'
    line: "synchronous_standby_names = '{{ pgsqlrep_application_name }}'"

  - regexp: '#?synchronous_commit = \w+(\s+#.*)'
    line: 'synchronous_commit = {{ pgsqlrep_synchronous_commit }}\1'
