---
- hosts: db
  become: yes

  roles:
    - geerlingguy.mysql
      # ATENCIÓN. ESTE ROLE LLEVA UN CAMBIO PARA EVITAR UN ERROR OCASIONAL AL EJECUTAR EL PLAYBOOK.
      # DA ERRORES CUANDO HACES VAGRANT PROVISION Y YA ESTABAN CREADOS LOS USUARIOS DE MySQL
      # PORQUE (item=(censored due to no_log)) => {"censored": "the output has been ...
      # ESTE CAMBIO (AÑADIR ignore_errors: true EN LA TAREA "Ensure MySQL users are present.")
      # SE HACE DIRECTAMENTE SOBRE EL ROLE.
      # CUIDADO EN REINSTALACIONES DE ROLE REQUIREMENTS, SE PIERDE ESTE CAMBIO.
      # VER roles/geerlingguy.mysql/tasks/user.ml, LINEA 13.
