---
- hosts: monitoring     # era ubuntu1604 en "MetalBootstrap"
  become: true          # hace falta sudo

  tasks:
  - name: package update (apt)
    apt: update_cache=yes cache_valid_time=3600

  - name: Install nginx 
    action: apt pkg=nginx state=present

  - name: Copy nginx config file to /etc/nginx/nginx.conf
    copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf

  - name: Remove nginx default site
    file: >
      dest=/etc/nginx/sites-available/default
      state=absent

  - name: Copy nginx vhost config file for proxypass # SEE files/proxypass.conf
    copy: src=files/proxypass.conf dest=/etc/nginx/sites-available/proxypass.conf

  - name: Enable configuration for proxypass
    file: >
      dest=/etc/nginx/sites-enabled/proxypass.conf
      src=/etc/nginx/sites-available/proxypass.conf
      state=link

  - name: Restart nginx
    service: name=nginx state=restarted
