---
# THESE DEFAULTS SHOULD BE OVERWRITTEN, DEPENDING ON THE GROUP OR HOST,
# THROUGH group-vars OR hostvars DEFINED VARIABLES
# OVERWRITTEN THROUGH hostvars DEFINED VARIABLES
#firewall_state: started
#firewall_enabled_at_boot: true
#firewall_allowed_tcp_ports:
#  - "22"   # ssh
#  - "25"   # postfix
#  - "80"   # http
#  - "123"  # ntp
#  - "443"  # https
#  - "2812" # monit web interface
#  - "3306" # mysql-server
#  - "4949" # munin
#  - "5044" # logstash_listen_port_beats
#  - "5400" # filebeat
#  - "5432" # postgresql
#  - "5601" # kibana
#  - "5666" # nagios-nrpe-server-port
#  - "9200" # elasticsearch
#  - "9292" # puma
#
#firewall_additional_rules:
#  # Allow mysql-replication traffic from mysql-master (192.168.2.30)
#  # We don´t know what will be the port being called
#  - "iptables -A INPUT -p tcp -s 192.168.2.30 -j ACCEPT"
#  # Ignore Dropbox LAN Sync broadcasts(17500) and similars (137, 138)
#  - "iptables -A INPUT -p udp -m udp --dport 17500 -j DROP"
#  - "iptables -A INPUT -p udp -m udp --dport 137 -j DROP"
#  - "iptables -A INPUT -p udp -m udp --dport 138 -j DROP"
