---
- import_playbook: postgres/main.yml
- import_playbook: nginx/main.yml
- import_playbook: railsapp/main.yml

- import_playbook: elk/main.yml

- import_playbook: common/monit/main.yml
- import_playbook: common/beats/main.yml

- import_playbook: common/backup/main.yml
- import_playbook: common/firewall/main.yml
- import_playbook: common/logrotate/main.yml
- import_playbook: common/ntp/main.yml
- import_playbook: common/security/main.yml
