---
# THESE TASKS ARE INCLUDED IN THE deploy.yml PLAYBOOK
# THEY SET NGINX UPSTREAM AND PUMA GEM, CONFIG AND UPSTART FILES (IF DESIRED)  
- name: Ensure present nginx upstream-loadbalancer config for railsapp-puma 
  template:
    src: templates/{{ app_name }}.conf.j2
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0664
  when: inventory_hostname == groups.app[0] # ONLY ONCE PER GROUP
  delegate_to: "{{ groups['web'][0] }}"
  notify: restart nginx

- name: Ensure Unicorn gem absent of Gemfile
  lineinfile:
    path: "{{ app_directory }}/Gemfile"
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '# Use Unicorn as the app server'
    - "gem 'unicorn'"

- name: Ensure Puma gem present at Gemfile
  lineinfile:
    path: "{{ app_directory }}/Gemfile"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {
      regexp: '# Use Puma as the app server',
      line: "# Use Puma as the app server"
    }
    - {
      regexp: "gem 'puma'",
      line: " gem 'puma', group: :production"
    }

- name: Ensure puma.rb configuration file is present.
  template:
    src: templates/config-puma.rb.j2
    dest: "{{ app_directory }}/config/puma.rb"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0664

- name: Ensure puma pids and socket folders exist and writeable.
  file:
    path: "{{ app_directory }}/tmp/{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0755
  with_items:
    - pids
    - sockets

#========  PUMA COMMANDS BASH SCRIPT  ==================================================
# SCRIPT puma WILL BE PLACED AT /usr/local/bin/puma WITH COMMANDS TO MANAGE PUMA
# Usage: puma {start|stop|restart|phased-restart|kill_worker 0,1,etc} [requires sudo rights]
# SEE https://gist.github.com/sudara/8653130
# AND /playbooks/railsapp/templates/puma_commands.sh.j2
# AND /playbooks/common/monit/templates/service_checks/puma.j2
- name: Copy puma_commands script to server.
  template:
    src: puma_commands.sh.j2
    dest: /usr/local/bin/puma
    owner: root
    group: root
    mode: 0755
  when: "'app' in group_names"
#=======================================================================================
