---
# Variables for our app.
git_repository: https://github.com/antoniovelazquezbarroso/myticketee_3db.git
git_version: mysql        # Allows choosing the version of the repo
                          # Here it is the relevant branch name
app_name : railsapp
app_directory: /opt/{{ app_name }}
app_user: deployer
app_secrets:
  dev: fe562ec1e21eecc5af4d83f6a157a7
  test: 4408f36dd290766d2f368fdfcedf4d
  prod: 9bf801da1a24c9a103ea86a1438caa
app_environment:
  RAILS_ENV: production

# Variables for Ruby installation.
ruby_install_from_source: true
ruby_download_url: http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.0.tar.gz
ruby_version: 2.2.0

deploying_with_capistrano: false
monitoring_with_god: false

